services:
  db:
    image: postgres:latest
    container_name: pg-server
    restart: always
    environment:
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_USER: postgres
      POSTGRES_DB: meu_projeto_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - rede-banco

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - rede-banco

networks:
  rede-banco:
    driver: bridge

volumes:
  pgdata:
